"""Change model name Orders to Order

Revision ID: 584c839c2ac9
Revises: a4b6bc538bd8
Create Date: 2024-06-25 22:37:03.314489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584c839c2ac9'
down_revision: Union[str, None] = 'a4b6bc538bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_shop_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'products', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('shops_owner_id_fkey', 'shops', type_='foreignkey')
    op.create_foreign_key(None, 'shops', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_favorite_product_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'products', ['favorite_product_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_favorite_product_id_fkey', 'users', 'products', ['favorite_product_id'], ['id'])
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.create_foreign_key('shops_owner_id_fkey', 'shops', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_shop_id_fkey', 'products', 'shops', ['shop_id'], ['id'])
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
