"""Try fix maps problem Order -> User 

Revision ID: 695d97e9cd52
Revises: d2c33ea1d299
Create Date: 2024-06-25 22:51:47.823747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695d97e9cd52'
down_revision: Union[str, None] = 'd2c33ea1d299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
