"""Try fix maps problem Order -> User last

Revision ID: 7b35c0a00d15
Revises: 695d97e9cd52
Create Date: 2024-06-25 22:53:39.476032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b35c0a00d15'
down_revision: Union[str, None] = '695d97e9cd52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_date', sa.DateTime(), nullable=True))
    op.drop_constraint('orders_product_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('orders', 'edited')
    op.drop_column('orders', 'created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('edited', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key('orders_product_id_fkey', 'orders', 'products', ['product_id'], ['id'])
    op.drop_column('orders', 'order_date')
    # ### end Alembic commands ###
